const canvas = document.querySelector('#milky-way');
const enter = document.querySelector('#enter');
const wish = document.querySelector('#wish');
const ctx = canvas.getContext('2d');
const reducedMotion = matchMedia('(prefers-reduced-motion: reduce)').matches;
const lowPower = reducedMotion || (navigator.hardwareConcurrency && navigator.hardwareConcurrency <= 4) || (navigator.deviceMemory && navigator.deviceMemory <= 4);
const scene = { width: 0, height: 0, scale: 1, opened: false, last: 0, nextMeteor: 0, stars: [], meteors: [], pointer: { x: 0, y: 0 } };

function randomStar() { return { x: Math.random(), y: Math.random(), size: Math.pow(Math.random(), 2.4) * 2.6 + .22, phase: Math.random() * Math.PI * 2, hue: Math.random() > .8 ? 216 : 202 }; }
function resize() { scene.scale = Math.min(devicePixelRatio || 1, lowPower ? 1 : 1.5); scene.width = innerWidth; scene.height = innerHeight; canvas.width = Math.round(scene.width * scene.scale); canvas.height = Math.round(scene.height * scene.scale); ctx.setTransform(scene.scale,0,0,scene.scale,0,0); scene.pointer.x = scene.width*.5; scene.pointer.y = scene.height*.5; scene.stars = Array.from({ length: scene.width < 700 ? 36 : lowPower ? 54 : 82 }, randomStar); }
function drawStars(time) { const shiftX=(scene.pointer.x-scene.width*.5)*.012, shiftY=(scene.pointer.y-scene.height*.5)*.012; ctx.save(); ctx.globalCompositeOperation='screen'; scene.stars.forEach((star)=>{ const alpha=.13+(Math.sin(time*.0011+star.phase)+1)*.17, x=star.x*scene.width+shiftX*(star.size*5), y=star.y*scene.height+shiftY*(star.size*5); ctx.beginPath(); ctx.arc(x,y,star.size,0,Math.PI*2); ctx.fillStyle=`hsla(${star.hue},100%,92%,${alpha})`; ctx.fill(); if(star.size>1.65){ ctx.beginPath(); ctx.moveTo(x-star.size*4,y); ctx.lineTo(x+star.size*4,y); ctx.moveTo(x,y-star.size*4); ctx.lineTo(x,y+star.size*4); ctx.strokeStyle=`rgba(214,238,255,${alpha*.5})`; ctx.lineWidth=.55; ctx.stroke(); } }); ctx.restore(); }
function spawnMeteor(start=performance.now()) { scene.meteors.push({ start, x:scene.width*(-.14+Math.random()*.7), y:scene.height*(-.18+Math.random()*.26), dx:scene.width*(.29+Math.random()*.18), dy:scene.height*(.38+Math.random()*.21), width:Math.random()>.72?1.65:1.05 }); }
function drawMeteors(time) { scene.meteors=scene.meteors.filter((meteor)=>time-meteor.start<1250); scene.meteors.forEach((meteor)=>{ const elapsed=time-meteor.start; if(elapsed<0)return; const progress=elapsed/1250, x=meteor.x+progress*meteor.dx, y=meteor.y+progress*meteor.dy, length=Math.hypot(meteor.dx,meteor.dy)||1, tail=118*(1-progress), tailX=x-tail*meteor.dx/length, tailY=y-tail*meteor.dy/length; const trail=ctx.createLinearGradient(x,y,tailX,tailY); trail.addColorStop(0,`rgba(255,255,255,${1-progress})`); trail.addColorStop(.18,`rgba(193,224,255,${(1-progress)*.75})`); trail.addColorStop(1,'rgba(130,185,255,0)'); ctx.beginPath(); ctx.moveTo(x,y); ctx.lineTo(tailX,tailY); ctx.strokeStyle=trail; ctx.lineWidth=meteor.width; ctx.shadowBlur=11; ctx.shadowColor='#b9ddff'; ctx.stroke(); ctx.shadowBlur=0; }); }
function render(time) { const interval=lowPower?1000/30:0; if(time-scene.last<interval){requestAnimationFrame(render);return;} scene.last=time; if(scene.opened&&time>scene.nextMeteor){spawnMeteor(time);scene.nextMeteor=time+1800+Math.random()*2200;} ctx.clearRect(0,0,scene.width,scene.height); drawStars(time); drawMeteors(time); requestAnimationFrame(render); }
function openSky() { if(scene.opened)return; scene.opened=true; document.body.classList.add('opened'); const start=performance.now(); for(let i=0;i<(lowPower?4:8);i+=1)spawnMeteor(start+i*115); scene.nextMeteor=start+2200; }
function makeWish() { if(scene.opened)spawnMeteor(); }
canvas.addEventListener('pointermove',(event)=>{scene.pointer.x=event.clientX;scene.pointer.y=event.clientY;}); canvas.addEventListener('pointerdown',makeWish); enter.addEventListener('click',openSky); wish.addEventListener('click',makeWish); window.addEventListener('keydown',(event)=>{if(event.code==='Space'&&!event.repeat){event.preventDefault();scene.opened?makeWish():openSky();}}); window.addEventListener('resize',resize); resize(); requestAnimationFrame(render);
